apiVersion: apps/v1
kind: Deployment
metadata:
  name: badsound-counter-api
  namespace: bsc-backend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: badsound-counter-api
  template:
    metadata:
      labels:
        app: badsound-counter-api
    spec:
      containers:
        - name: webserver
          image: 463935167443.dkr.ecr.ap-northeast-2.amazonaws.com/badsound-counter-api:4304ea4
          env:
            - name: GOOGLE_FIREBASE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google-token
                  key: token
          ports:
            - containerPort: 8080
            - containerPort: 7007
