apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: badsound-counter-api
  namespace: bsc-backend-api
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "bsc.chuyong.kr"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "bsc.chuyong.kr"
      tls:
        mode: PASSTHROUGH