apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: badsound-counter-api
  namespace: bsc-backend-api
spec:
  hosts:
    - "bsc.chuyong.kr"
  gateways:
    - badsound-counter-api
  tls:
    - match:
        - port: 443
          sniHosts:
            - "bsc.chuyong.kr"
      route:
        - destination:
            host: badsound-counter-api
            port:
              number: 80
  http:
    - name: "default-routes"
      route:
        - destination:
            host: badsound-counter-api
            port:
              number: 80