apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chois-webview
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: chois-webview
    server: 'https://kubernetes.default.svc'
  source:
    path: chois-webview/overlays/prod
    repoURL: 'git@github.com:CChuYong/chois-webview.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
