apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: 013969630346.dkr.ecr.ap-northeast-2.amazonaws.com/magcloud-backend-dev
  newTag: f951f7fc95c5931bf6372fbc4ba540f3e47257cd
